[package]
name = "rsa-naive-algo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
primes="0.3.0"
modinverse="0.1.1"
num="0.4.0"
elliptic-curve = "0.13.5"
k256 = "0.13.1"
